runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: assets/index.html
  upload: assets/index.html
  secure: always

# - url: /(.*)
#   static_files: assets/\1
#   upload: assets/(.*)

- url: /(.*\..*)
  static_files: assets/\1
  upload: assets/(.*)

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
